canariecaf/adfstoolkit

ADFSToolkit/config/config.ADFSTk.default_en.xml

Initial default config file

---

ADFSToolkit/Public/Import-ADFSTkMetadata.ps1

[x] Enforce RunAsAdministrator level privileges for script

Require RunAsAdministrator

---

ADFSToolkit/ADFSToolkit.psd1

[x] resolved FunctionsToExport warnings of too broad export
[x] resolved spaces in tags for Powershell Gallery

adjusted Powershell Gallery restrictions

---

ADFSToolkit/ADFSToolkit.psd1
ADFSToolkit/ADFSToolkit.psm1
ADFSToolkit/Private/Update-SHA256AlgXmlDSigSupport.ps1
ADFSToolkit/Private/Verify-ADFSTkSigningCert.ps1
ADFSToolkit/Public/Import-ADFSTkMetadata.ps1
ADFSToolkit/Public/New-ADFSTkConfiguration.ps1
ADFSToolkit/Public/Unpublish-ADFSTkAggregate.ps1
ADFSToolkit/Unpublish-ADFSTkAggregate.ps1

Migrate 0.9.1 dev work to master branch

---

ADFSToolkit/ADFSToolkit.psd1
ADFSToolkit/Private/Get-ADFSTkTransformRule.ps1
ADFSToolkit/config/default/en-US/config.ADFSTk.default_en.xml

[x] improved claim mapping for group ePA/ePSA mapping
[x] improved template offering static, dynamic, and attribute based origin of ePA/ePSA
[x] reved build number to .40

Dynamic eduPersonAffiliation and ePSA handling

---

ADFSToolkit/Private/Add-ADFSTkSPRelyingPartyTrust.ps1
ADFSToolkit/Private/Import-ADFSTkIssuanceTransformRuleCategories.ps1

This is what we talked about today

Added support for reading Secure Hash SHA1/SHA256 from metadata.

---

ADFSToolkit/ADFSToolkit.psd1
ADFSToolkit/Private/Set-ADFSTkConfigItem.ps1
ADFSToolkit/Public/New-ADFSTkConfiguration.ps1

This update adds the ability to pull forward old configurations into the new environment

Chris dev - enhancement to pipeline old configurations into new

---

ADFSToolkit/Private/Add-ADFSTkSPRelyingPartyTrust.ps1
ADFSToolkit/Private/Get-ADFSTkIssuanceTransformRules.ps1
ADFSToolkit/Private/Import-ADFSTkAllAttributes.ps1
ADFSToolkit/Private/Import-ADFSTkAllTransformRules.ps1
ADFSToolkit/Private/Import-ADFSTkIssuanceTransformRuleCategories.ps1
ADFSToolkit/Private/Processes-ADFSTkRelyingPartyTrust.ps1
ADFSToolkit/Public/Import-ADFSTkMetadata.ps1

Added some Event IDs
Added support for SQL store
Added NameID, missed from last feature
CHanged default cachetime from 60 to 15 minutes

This resolve #61, closes #62, close #65

---

ADFSToolkit/Private/Add-ADFSTkSPRelyingPartyTrust.ps1
ADFSToolkit/Private/Get-ADFSTkSamlResponseSignature.ps1
ADFSToolkit/config/default/get-ADFSTkLocalManualSPSettings-dist.ps1

Don't think I need to add a review.  We talked about this code earlier today.

This solves #95

---

ADFSToolkit/ADFSToolkit.psd1
ADFSToolkit/ADFSToolkit.psm1
ADFSToolkit/Private/Set-ADFSTkInstitutionConfiguration.ps1
ADFSToolkit/Public/Disable-ADFSTkInstitutionConfiguration.ps1
ADFSToolkit/Public/Update-ADFSTkInstitutionConfiguration.ps1
ADFSToolkit/languagePacks/en-US/ADFSTk_en-US.pson

ingest the enable/disable adfstkconfiguration directives for testing

ingest changes for validation

---

README.md
doc/README.md
doc/upgrade.md

Documentation for v2 is now more current with:

Refactored Documetation

---

ADFSToolkit/Private/Copy-ADFSTkFile.ps1
ADFSToolkit/Public/New-ADFSTkInstitutionConfiguration.ps1

Created a new function Copy-ADFSTkItem that takes the same -Path and -Destination as Copy-Item.
This copies all lines until the signature starts.

This solves #123

---

ADFSToolkit/Private/Get-ADFSTkEnhancedRule.ps1
ADFSToolkit/Private/Get-ADFSTkIssuanceTransformRules.ps1
ADFSToolkit/languagePacks/en-US/ADFSTk_en-US.pson

Now with support for multiple transforms.

This solves #136

---

ADFSToolkit/ADFSToolkit.psd1

fix (bug): tags cannot contain spaces

---

doc/README.md

sync doc changes from upstream

---

src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters.csproj
src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/Constants.cs
src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/LoginPasswordHtml.txt
src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/RefedsMFAUsernamePasswordMetadata.cs
src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/RefedsSFAUsernamePasswordMetadata.cs
src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/Resources/StringResources.en.resx

Fixed javascript, and some other details

---

ADFSToolkit/Private/Import-ADFSTkAllTransformRules.ps1

It can now handle T-numbers and other Letters or with the 4 last digits left out.

Fixed Regex

---

ADFSToolkit/Private/Initialize-ADFSTk.ps1
ADFSToolkit/Public/Update-ADFSTkInstitutionConfiguration.ps1
ADFSToolkit/config/default/config.ADFSTk.default.xml

Added pairwise-id and subject-id to Default Config file

Updated XML config version to 1.4

---

ADFSToolkit/config/default/get-ADFSTkLocalManualSPSettings-dist.ps1

Already support for MFA Push and enter number, remove incorrect comment

This solves #197

---

src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters.csproj
src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/Constants.cs
src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/LangText.cs
src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/LoginPasswordHtml.txt
src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/Properties/AssemblyInfo.cs
src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/ResourceHandler.cs
src/ADFSToolkitRefedsAdapters/ADFSToolkitRefedsAdapters/UsernamePasswordPresentation.cs

Feature adfstkstore split
